return {
    [0] = { id = 0, en = "---" },
    [1] = { id = 1, en = "WAR" },
    [2] = { id = 2, en = "MNK" },
    [3] = { id = 3, en = "WHM" },
    [4] = { id = 4, en = "BLM" },
    [5] = { id = 5, en = "RDM" },
    [6] = { id = 6, en = "THF" },
    [7] = { id = 7, en = "PLD" },
    [8] = { id = 8, en = "DRK" },
    [9] = { id = 9, en = "BST" },
    [10] = { id = 10, en = "BRD" },
    [11] = { id = 11, en = "RNG" },
    [12] = { id = 12, en = "SAM" },
    [13] = { id = 13, en = "NIN" },
    [14] = { id = 14, en = "DRG" },
    [15] = { id = 15, en = "SMN" },
    [16] = { id = 16, en = "BLU" },
    [17] = { id = 17, en = "COR" },
    [18] = { id = 18, en = "PUP" },
    [19] = { id = 19, en = "DNC" },
    [20] = { id = 20, en = "SCH" },
    [21] = { id = 21, en = "GEO" },
    [22] = { id = 22, en = "RUN" }
    ,
}, { "id", "en" }
